In [4]:
%load_ext autoreload
%autoreload 2

In [67]:
import pandas as pd
import sys
import regression_tree as rt
import prediction_evaluation as eval
import grid_search
sys.path.append("preprocessing")
import preprocessing_food_wastage as pre_food_wastage
import preprocessing_college_ranking as pre_college_ranking

In [72]:
food_waste_df_train, food_waste_df_test = pre_food_wastage.preprocessing_food_wastage()
college_rank_df_train, college_rank_df_test = pre_college_ranking.preprocessing_college_ranking()

C:\Users\teoes\OneDrive\Dokument\GitHub\Machine_learning_WS_2025\A2\preprocessing\preprocessing_general.py:10: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  return pd.get_dummies(df, columns=columns_for_ohe).replace({True: 1, False: 0})
C:\Users\teoes\OneDrive\Dokument\GitHub\Machine_learning_WS_2025\A2\preprocessing\preprocessing_general.py:10: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  return pd.get_dummies(df, columns=columns_for_ohe).replace({True: 1, False: 0})

In [76]:
param_grid = {
    'min_samples_split': range(5,7,1),
    'max_depth': range(1,3,1),
    'split_criterion': ['sse']
}


param_grid_scikit = {
    'min_samples_split': range(5,7,1),
    'max_depth': range(2,3,1),
    'criterion': ['squared_error']
}

In [ ]:
best_tree_food_waste, train_results_food_waste = grid_search.grid_search_cv(food_waste_df_train, "wastage_food_amount", rt.regression_tree, rt.predict_from_tree, param_grid)
train_results_food_waste

Running combo: 1
Running combo: 2
Running combo: 3
Running combo: 4

      runtime  mean_score                                         Parameters
0  234.586915    6.149970  {'min_samples_split': 5, 'max_depth': 2, 'spli...
1  161.921353    6.181246  {'min_samples_split': 6, 'max_depth': 2, 'spli...
2  128.982467    6.343354  {'min_samples_split': 6, 'max_depth': 1, 'spli...
3  127.462756    6.730587  {'min_samples_split': 5, 'max_depth': 1, 'spli...

In [ ]:
food_waste_predictions_reg_tree = rt.predict_from_tree(best_tree_food_waste, food_waste_df_test)
food_waste_rmse_reg_tree = eval.rmse(food_waste_df_test["wastage_food_amount"], food_waste_predictions_reg_tree)
print(f"RMSE score on test set: {food_waste_rmse_reg_tree}")

RMSE score on test set: 5.576393396194763

In [ ]:
sci_kit_results_food_waste, best_tree_scikit_food_waste = grid_search.grid_search_scikit(food_waste_df_train, "wastage_food_amount", param_grid_scikit)
sci_kit_results_food_waste

Fitting 5 folds for each of 2 candidates, totalling 10 fits
DecisionTreeRegressor(max_depth=2, min_samples_split=5, random_state=1)
Time(s):  0.12425510003231466

,runtime,mean_test_score,params
0,0.124255,5.555888,"{'criterion': 'squared_error', 'max_depth': 2,..."
1,0.124255,5.555888,"{'criterion': 'squared_error', 'max_depth': 2,..."

In [ ]:
food_waste_predictions_reg_tree_scikit = best_tree_scikit_food_waste.predict(food_waste_df_test.loc[:, food_waste_df_test.columns != "wastage_food_amount"])
food_waste_rmse_reg_tree_scikit = eval.rmse(food_waste_df_test["wastage_food_amount"], food_waste_predictions_reg_tree_scikit)
print(f"Food waste RMSE score on test set: {food_waste_rmse_reg_tree}")
print(f"Food waste RMSE score on test set using Scikit implementation: {food_waste_rmse_reg_tree_scikit}")

RMSE score on test set: 5.576393396194763
RMSE score on test set using Scikit implementation: 5.576393396194763

In [74]:
best_tree_college_rank, train_results_college_rank = grid_search.grid_search_cv(college_rank_df_train, "2023", rt.regression_tree, rt.predict_from_tree, param_grid)
train_results_college_rank

Running combo: 1
Running combo: 2
Running combo: 3
Running combo: 4

     runtime  mean_score                                         Parameters
0  10.122125   17.862607  {'min_samples_split': 5, 'max_depth': 2, 'spli...
1  10.194577   17.950506  {'min_samples_split': 6, 'max_depth': 2, 'spli...
2   6.734903   19.472643  {'min_samples_split': 6, 'max_depth': 1, 'spli...
3   6.720323   22.587867  {'min_samples_split': 5, 'max_depth': 1, 'spli...

In [75]:
college_rank_predictions_reg_tree = rt.predict_from_tree(best_tree_college_rank, college_rank_df_test)
college_rank_rmse_reg_tree = eval.rmse(college_rank_df_test["2023"], college_rank_predictions_reg_tree)
print(f"College rank RMSE score on test set: {college_rank_rmse_reg_tree}")

College rank RMSE score on test set: 14.590553112495714

In [77]:
sci_kit_results_college_rank, best_tree_scikit_college_rank = grid_search.grid_search_scikit(college_rank_df_train, "2023", param_grid_scikit)
sci_kit_results_college_rank

Fitting 5 folds for each of 2 candidates, totalling 10 fits
DecisionTreeRegressor(max_depth=2, min_samples_split=5, random_state=1)
Time(s):  0.1855406000977382

,runtime,mean_test_score,params
0,0.185541,13.459922,"{'criterion': 'squared_error', 'max_depth': 2,..."
1,0.185541,13.459922,"{'criterion': 'squared_error', 'max_depth': 2,..."

In [79]:
college_rank_predictions_reg_tree_scikit = best_tree_scikit_college_rank.predict(college_rank_df_test.loc[:, college_rank_df_test.columns != "2023"])
college_rank_rmse_reg_tree_scikit = eval.rmse(college_rank_df_test["2023"], college_rank_predictions_reg_tree_scikit)
print(f"Food waste RMSE score on test set: {college_rank_rmse_reg_tree}")
print(f"Food waste RMSE score on test set using Scikit implementation: {college_rank_rmse_reg_tree_scikit}")

Food waste RMSE score on test set: 14.590553112495714
Food waste RMSE score on test set using Scikit implementation: 12.443080616026744